### ISSUE TITLE
Log info in the job

### ISSUE THREAD

**Issue by nicolaeabacioaiei** [BogdanB01/FiiPractic2018#6]
https://github.com/BogdanB01/FiiPractic2018/blob/8e756647ecc7d0a0e0239be42fef8c6174686c68/src/main/java/com/fiipractic/health/control/tasks/ScheduledTask.java#L25

Every time the job runs you should log information like how many appointments were processed by the job.

The job should have his own log file.

**Comment by BogdanB01** [comment]
This was fixed. Please see https://github.com/BogdanB01/FiiPractic2018/commit/03d24452ea771a58aca2c8253afea1d12e48209a
